version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:-mydatabase}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: